### PR TITLE
Passing data when form submit in get as well

### PR DESCRIPTION
**Pull request by duduklein**
The `data-ajax-submit` form submission was not submitting the form data when using the GET method. Only the post one.

I included the form data in the ajaxGet call

### CODE REVIEW

**Comment by yceruto** [comment]
Thanks for your contribution. Could you please refactor this implementation to use `ajaxMethod` function instead? Something like that:
```js
method = method ? method.toLowerCase() : 'get';

ajaxMethod(method, url, data, function(content){
    var response = {};
    response.content = content;
    processData(response, $form);
}, options);
```

Thanks.

**Comment by duduklein** [comment]
Sure,
Which tool to you use to minify the js? 
As I only added one parameter, it was quite easy to modify the minified version.
Thanks

**Comment by yceruto** [comment]
https://github.com/mishoo/UglifyJS

**Comment by duduklein** [comment]
Hi, I have made the change you suggested.
I used uglifyjs with no options and removed the copyright by hand (the option -nc as not working).
Let me know if this is ok
Thanks

**Comment by yceruto** [comment]
Thanks you @duduklein

**Pull request merged**
